version: '3.8'
services:
  transaction:
    build: transaction
    ports:
      - "3001:8080"
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
