import Head from "next/head";
import Image from "next/image";
import { Line } from "@nivo/line";
import { Layout } from "../components/Layout";

import React, { useEffect, useState } from "react";
import { Graph } from "../components/Graph";
import Link from "next/link";

export default function Home() {
  const [speed, setSpeed] = useState(50);
  const [simulate, setSimulate] = useState(false);

  useEffect(() => {
    const interval = setInterval(() => {
      console.log("This will run every second!");
    }, 1000);
    return () => clearInterval(interval);
  }, [simulate]);

  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h2 className="text-4xl font-bold tracking-tight  sm:text-6xl pb-4">Admin dashboard</h2>
        <input
          type="range"
          name="speed"
          id="speed"
          value={speed}
          onChange={(e) => setSpeed(Number(e.target.value))}
          min={0}
          max={100}
        />
        <button onClick={() => setSimulate((s) => !s)} className="text-xl">
          Start Autotrader
        </button>
      </Layout>
    </>
  );
}
